### ISSUE TITLE
Incorrect disassembly

### ISSUE THREAD

**Issue by tathanhdinh** [B2R2-org/B2R2#1]
(many thanks for this new framework, I'm just discovering it)

**Describe the bug**
Incorrect disassembly of instruction
```Assembly
44 0f 20 c0    mov rax, cr8
```

**To Reproduce**
1. Run this piece of code
```F#
open B2R2
open B2R2.FrontEnd

[<EntryPoint>]
let main argv =
  let isa = ISA.OfString "amd64"
  let bytes = [| 0x44uy; 0x0fuy; 0x20uy; 0xc0uy |]
  let handler = BinHandler.Init (isa, bytes)
  let ins = BinHandler.ParseInstr handler 0UL
  ins
  |> fun i -> i.Disasm ()
  |> printfn "%s"
  0
```
2. See output
```Assembly
mov eax, cr0
```

**Expected behavior**
```Assembly
mov rax, cr8
```

**Environment (please complete the following information):**
 - OS: Windows 7 x64
 - .NET Core version: 2.2.104
 - B2R2 version: latest from Github

**Comment by sangkilc** [comment]
Thanks for the report :+1: 

We will fix this issue ASAP.

**Comment by tathanhdinh** [comment]
Thanks for the prompt response @sangkilc .
As said, I'm just discovering B2R2 (hopefully can contribute someday).
