### ISSUE TITLE
AND instruction not correctly lifted

### ISSUE THREAD

**Issue by enkomio** [B2R2-org/B2R2#10]
**Describe the bug**
The following x86 instruction:

    and eax, 0xFFFF0000

is lifted to the following statements:

    T_0:I32 := (EAX & 0xFFFF0000:I32)
    EAX := T_0:I32
    OF := 0x0:I1
    CF := 0x0:I1
    AF := Undefined expression (AF is undefined.)

**To Reproduce**
Consider the following F# program:

	let handler = 
		BinHandler.Init(
			ISA.OfString "x86", 
			ArchOperationMode.NoMode, 
			FileFormat.RawBinary, 
			Addr.MinValue, 
			[|0x25uy; 0x00uy; 0x00uy; 0xFFuy; 0xFFuy|] // and eax, 0xFFFF0000
		)

	let instruction = BinHandler.ParseInstr handler 0UL
	let statements = BinHandler.LiftInstr handler instruction

	let statementString = LowUIR.Pp.stmtToString statements.[5]
	Console.WriteLine(statementString)

It produces the following output:

	AF := Undefined expression (AF is undefined.)	

**Expected behavior**
A correct LowUIR statement should be composed

**Environment (please complete the following information):**
 - OS: Windows
 - B2R2 version: 0.1.0

**Additional context**
The test was done by using .NET Framework 4.7.

**Comment by sangkilc** [comment]
Thanks for the report.

Are you saying that the AF flag is wrong? In fact, that's the expected behavior of AND instruction: https://x86.puri.sm/html/file_module_x86_id_12.html. See the line:
> The OF and CF flags are cleared; the SF, ZF, and PF flags are set according to the result. The state of the AF flag is undefined.

Typically AF will be re-set by following instructions.

**Comment by enkomio** [comment]
thanks for the answer. So when I encounter an Undefined statement is not necessary an error right?

I supposed it was an error due to the comment:

```
/// Undefined expression. It is a fatal error when we encounter this
/// expression while evaluating a program. This expression is useful when we
/// encode a label that should not really jump to (e.g., divide-by-zero
/// case).
```

**Comment by enkomio** [comment]
Ok, I think got it, it is only an error during evaluation but it is considered a "valid" expression.

**Comment by sangkilc** [comment]
Yes you're right :)
