### ISSUE TITLE
How to update the binary handler content?

### ISSUE THREAD

**Issue by enkomio** [B2R2-org/B2R2#11]
Hi,

I'm creating a simple emulator for LowUIR and during my test I need to modify the content of the Binary Handler (as in a self modifying program).

As far as I understood the only way in doing this is by using the ``BinHandler.UpdateCode`` function, that return a new handler. The function accepts an array of bytes that represent the full content of the new handler. This is a bit annoying if I have to modify just a couple of bytes (but I understand that you want to maintain BinHandler immutable). 

My current strategy is:
  - Convert the VA with a raw offset inside the buffer
  - Read the handler buffer and modify the given bytes at the calculated offset
  - create an handler with the update buffer

Is there any other easier way of doing this or what I described is the proper way?

**Comment by sangkilc** [comment]
As you described, we would like to make the handler immutable, and what you described is okay, but I would simply maintain the original buffer (`byte []`) somewhere in your code, and modify the buffer before you create a new handler. This way, you can eliminate the second step.

Originally, the UpdateCode function was designed to be used to parse dynamic execution traces where we can read a basic-block-level code chunk at a time. In this case, we need to frequently update the code, and creating a new handler was not a big deal. In your use case, however, creating a new BinHandler all the time will be largely redundant as you pointed out. Maybe we should create a mutable-version of BinHandler (something like `MutableBinHandler`).

**Comment by sangkilc** [comment]
Actually, I think we can address your concern by modifying the `BinReader` class in such a way that it can have a setter. We are currently cleaning up the BinFile and BinReader module, so we will try to fix this issue in the next release. In the meantime, you can stick to your current strategy.

**Comment by enkomio** [comment]
Thanks for the suggestion. I'll do as you said, while I wait for the next release :)

**Comment by sangkilc** [comment]
I am reopening the issue so that we don't forget.

**Comment by sangkilc** [comment]
Please checkout: 40e7be659ede4305cc36630e38fbc462525f2943

You should now be able to modify the buffer by:
```fsharp
// hdl = BinHandler
hdl.FileInfo.BinReader.Bytes.[idx] <- byteValue
```

Or even by:
```fsharp
hdl.FileInfo.BinReader.Bytes <- newArray
```
