### ISSUE TITLE
Error in parse export for DLL profapi.dll

### ISSUE THREAD

**Issue by enkomio** [B2R2-org/B2R2#16]
**Describe the bug**
When a BinHandler is created, the code in charge for parsing the *Export table* raise an exception. The problematic file is ``C:\Windows\SysWOW64\profapi.dll`` (MD5: *2545F5AA189DF907BC4A6E000E231A6D*).

**To Reproduce**
1. Run code: ``BinHandler.Init(ISA.OfString "x86", @"C:\Windows\SysWOW64\profapi.dll")``
2. See error in ``PEHelper.getRawOffset``, exception message: ``System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'``

**Environment (please complete the following information):**
 - OS: Windows
 - B2R2 version: 0.1.1 (2019-03-22)

**Additional context**
The DLL contains a uncommon Export directory table, an example of export is:

    Ordinal        Function RVA   Name Ordinal    Name RVA    Name
    00000066	00004560	N/A	      N/A	  N/A

This will raise an exception at the following code:
``let sHdr = headers.SectionHeaders.[idx]``
where ``idx`` has value ``-1``.

**Comment by sangkilc** [comment]
Thanks for reporting this bug. Could you upload the file somewhere?

**Comment by enkomio** [comment]
Sure: https://www.sendspace.com/file/tsawci

**Comment by sangkilc** [comment]
Awesome. Will take a look at this ASAP.

**Comment by sangkilc** [comment]
44d2c8a7c3d92de270a9cfd886c99434b730d931 should fix the issue. Please close the issue if it works for you.

**Comment by enkomio** [comment]
It works like a charm. Thank you very much for your promptly fix :)
