### ISSUE TITLE
Improve Segmentation Semantics for x86

### ISSUE THREAD

**Issue by tathanhdinh** [B2R2-org/B2R2#2]
**Describe the bug**
LowIR for instructions accessing segmented memory is "probably" incorrect, e.g.
```Assembly
2e 8b 02    mov eax, cs:[edx]
```

**To Reproduce**
1. Run this piece of code
```F#
open B2R2
open B2R2.FrontEnd

[<EntryPoint>]
let main argv =
  let isa = ISA.OfString "x86"
  let bytes = [| 0x2euy; 0x8buy; 0x02uy; |]
  let handler = BinHandler.Init (isa, bytes)
  let ins = BinHandler.ParseInstr handler 0UL
  ins
  |> fun i -> i.Translate handler.TranslationContext
  |> printfn "%A"
  0
```

2. See output

```Lisp
[|ISMark (0UL,3u);
  Put
    (Var (32,8,"EAX",IntelRegisterSet<1, 0, 0, 0>),
     Load
       (Little,32,
        BinOp
          (ADD,32,Var (32,1793,"CSBase",IntelRegisterSet<8000000, 0, 0, 0>),
           Var (32,11,"EDX",IntelRegisterSet<8, 0, 0, 0>),
           {HasLoad = false;
            VarInfo = IntelRegisterSet<8000008, 0, 0, 0>;
            TempVarInfo = set [];},None),
        {HasLoad = true;
         VarInfo = IntelRegisterSet<8000008, 0, 0, 0>;
         TempVarInfo = set [];},None)); IEMark 3UL|]
```

**Expected behavior**
In the Intel's segmented memory model, the semantics of `cs:[edx]` is not simply as loading `[cs + edx]`.

**Environment:**
 - .NET Core version: [e.g. 2.1.502]
 - B2R2 version [e.g. 0.1.0]

**Additional context**
I'm reading the paper but it does not discuss about how the memory is modelled.

**Comment by sangkilc** [comment]
Note that we use a special variable "CSBase" here, which basically points to the base address of the cs segment. We intentionally omitted GDT-related semantics to simplify our IR, and this is really a low priority for us to correctly implement the semantics for segmentation. For now, it is the responsibility of the analyst (the analyzer) that needs to correctly compute the value of "CSBase". I am going to close this as this is not really a bug.

**Comment by sangkilc** [comment]
Well actually I am going to open this as "help wanted".

**Comment by tathanhdinh** [comment]
@sangkilc Thanks for the response, it makes sense to me.
Do you mean that the semantics of `Var (32,1793,"CSBase",IntelRegisterSet<8000000, 0, 0, 0>)` should depend on the selected memory model?
PS. Is there any "technical report" which describes in detail the semantics of `LowIR`? (in the main paper, it is just a figure) or is the source code the ultimate document?

**Comment by sangkilc** [comment]
I mean you can implement your own analyzer using a memory model that handles the CSBase variable correctly. For documentation, you should take a look at the file `LowUIR.fs`. There are extensive comments for each expression and statement of our IR.
