### ISSUE TITLE
Bug in GetSymbols

### ISSUE THREAD

**Issue by cha5126568** [B2R2-org/B2R2#25]
**Describe the bug**
Static 형태의 심볼을 가진 파일에서 주소를 가져올때 실제 주소가 아닌 섹션으로 부터의 오프셋만 가져옵니다.
![](https://kong.re.kr/b2r2_test/bug3.PNG)
**To Reproduce**
아래 코드를 실행하면 확인 할 수 있습니다.
```python
import clr
import os, sys

sys.path.append(os.path.abspath(r'./build/'))
clr.AddReferenceToFile(r'B2R2.Core.dll')
clr.AddReferenceToFile(r'B2R2.BinFile.dll')
clr.AddReferenceToFile(r'B2R2.FrontEnd.Core.dll')
clr.AddReferenceToFile(r'B2R2.FrontEnd.Library.dll')

from B2R2 import *
from B2R2.FrontEnd import *
import time


def search(result,dirname):
	filenames = os.listdir(dirname)
	for filename in filenames:
		full_filename = os.path.join(dirname, filename)
		if os.path.isdir(full_filename):
			search(result,full_filename)
		else:
			ext = os.path.splitext(full_filename)[-1]
			if ext == '.so' or ext == ".o": 
				result.append(full_filename)
	return result
def main():
	result = search([],r'libc_test\0ab7d53ae2c1f7d4a2e3535d422ea434\a\extracted')
	#result = search([],r'libc\0ab7d53ae2c1f7d4a2e3535d422ea434\lib\aarch64-linux-gnu')
	
	NameList_bss = ['global_max_fast','save_arena'] #bss
	NameList_data = ['main_arena'] #main_arena
	
	NameList = NameList_bss + NameList_data
	
	print len(result)
	for name in result:
		handler = BinHandler.Init(ISA.DefaultISA, name)
		for s in handler.FileInfo.GetSymbols():
			if s.Kind == BinFile.SymbolKind.ObjectType:   
				for name in NameList:
					if s.Name == name:
						print name, s
			
if __name__ == "__main__":
	main()
```
**Expected behavior**
주소를 가져올때 아래와 같은 값을 가져와야 한다고 생각합니다.
![](https://kong.re.kr/b2r2_test/bug1.PNG)
![](https://kong.re.kr/b2r2_test/bug2.PNG)

그러나 섹션 베이스가 빠진 값인 각각 0,0,8 을 얻어옵니다.

**Environment (please complete the following information):**
 - OS:  Windows 7
 - .NET Core version: 2.2.204
 - B2R2 version latest from github

**Additional context**
사용된 파일은 [여기](https://kong.re.kr/b2r2_test/b2r2_static_bug.7z)에서 다운로드 받을 수 있습니다.

**Comment by sangkilc** [comment]
리포트 고맙습니다. 정확히 어떤 함수/심볼에 대한 주소가 잘못되었다는 것인지 명확히 해주실 수 있을까요?

**Comment by sangkilc** [comment]
그림으로 짐작해 볼때,
`main_arena`의 주소가 0인 부분이 잘못되었다고 말씀하신 것 같지만, 0이 맞습니다. 6A10 은 단순히 파일 오프셋일 뿐이고 실제 심볼의 주소는 0이 들어가 있는게 맞습니다. object파일이기 때문에 relocation이전의 심볼은 당연히 0이 맞습니다. readelf를 통해 심볼 값을 보더라도 다음과 같이 나옵니다:
```
107: 0000000000000000  2184 OBJECT  LOCAL  DEFAULT    3 main_arena
```

다른 심볼 역시 마찬가지 입니다. 따라서 버그가 아닙니다.

**Comment by cha5126568** [comment]
해당함수의 Address는 RVA주소를 반환하는것이 아닌가요?
(레퍼런스가 없어서 조금 망설여지지만, 맞다고 가정하고 게속 이야기 하겠습니다. 아니라면 죄송합니다..ㅜㅜ)


readelf 의 --symbols 옵션은 심볼테이블의 정보를 보여주는것이라 그렇게 나오지만, 실제 relocation 이전의 주소는 그렇지 않습니다.  아래 두 경우를 봐주세요.

```
root@ubuntu:/tmp# gdb -q ./malloc.o
Reading symbols from ./malloc.o...(no debugging symbols found)...done.
(gdb) p &global_max_fast
$1 = (<data variable, no debug info> *) 0x7328 <global_max_fast>
(gdb) p &main_arena
$2 = (<data variable, no debug info> *) 0x6a10 <main_arena>
(gdb) p &malloc_init_state
$3 = (<text variable, no debug info> *) 0x0 <malloc_init_state>
```
실제 메모리상에서도 main_arena 가 0x6a10 위치에 위치합니다.

또 angr의 symbol을 얻어올때도 아래와 같이 동작합니다.

```python
import cle

p = cle.loader.Loader("malloc.o")
malloc_init_state = p.main_object.get_symbol("malloc_init_state")
main_arena = p.main_object.get_symbol("main_arena")
global_max_fast = p.main_object.get_symbol("global_max_fast")

print (hex(malloc_init_state.relative_addr))
print (hex(main_arena.relative_addr))
print (hex(global_max_fast.relative_addr))
```

```
0x0
0x6a10
0x7328
```

따라서 GetSymbols 함수가 Symbol Table의 정보를 그대로 가져오는것이 아니라, RVA값을 가져오는 목적이라면(실제 제가 b2r2를 활용하려고 하는 상황도 이 상황이고, 이 상황이 일반적일 것 같습니다.) 버그가 맞다고 생각합니다.

**Comment by sangkilc** [comment]
Object파일에 있는 변수들의 대한 주소를 지금 이야기 하고 있는 것이고, 따라서 실제 linking된 이후에는 그 주소가 달라질 수 밖에 없습니다. 따라서 gdb나 다른 툴에서는 해당 변수가 속하는 섹션의 파일 오프셋을 기반으로 임의의 주소를 부여한 것에 불과합니다. 예를 들면 main_arena의 경우에는 .data 섹션에 속하기 때문에 파일상에서 .data섹션의 위치는 0x6a50이고, .text섹션의 경우 0x40 부터 시작하기 때문에, .text섹션의 주소를 0으로 간주하고, .data섹션의 위치를 0x6a10으로 간주한 것 입니다. 하지만, 실제 링킹시에는 ,text섹션과 .data섹션의 위치가 변동될 수 있기 때문에 올바른 주소라고 볼 수 없습니다. 실제로 해당 파일의 .data 섹션의 주소는 0번지로 맵핑되어 있기도 하고, 여기서는 주소가 의미가 없기 때문에 이 문제를 버그라고 보기는 좀 어렵습니다.

하지만, 가상의 주소를 다른 툴과 동일한 휴리스틱을 적용해 계산하는 것은 역공학 측면에서 의미있는 일이라 판단되고, 따라서 이 이슈는 유효한 feature request라고 판단됩니다.

Fixed by 2bb21d685ebec2b7f8549dc92346fdbcebc1de50

**Comment by sangkilc** [comment]
Fixed by 2bb21d685ebec2b7f8549dc92346fdbcebc1de50

**Comment by cha5126568** [comment]
수정 감사합니다!

다만, 2bb21d6 커밋 이후로, 일부파일에서 다른 도구들과 다른 값을 반환합니다.
아래 경우를 봐주세요.
(문제가 되는 파일은 [여기](https://kong.re.kr/b2r2_test/libc-2.13.so) 에서 다운로드 받으실 수 있습니다.)

0.2.1 release
![](https://kong.re.kr/b2r2_test/on_0.2.1.png)

latest
![](https://kong.re.kr/b2r2_test/on_latest.PNG)

cutter(r2) / IDA
![](https://kong.re.kr/b2r2_test/cutter.PNG)
![](https://kong.re.kr/b2r2_test/ida.PNG)


기존(0x39a1c0) 과 다르게 BSS섹션의 VA가 한번 더 더해진 값(0x7330a0)을 반환합니다.
![](https://kong.re.kr/b2r2_test/die.PNG)
```0x7330a0-0x39a1c0=0x398ee0``` 이고, 이 파일에서 bss의 베이스가 0x398ee0 입니다. 저 커밋 이후로 잘못된 값을 반환하는 것 같습니다.

**Comment by sangkilc** [comment]
Should be fixed by 4ba0b9850c00cd10035336953387ee1edbe4df97
