### ISSUE TITLE
pcmpistri lifting infine loop

### ISSUE THREAD

**Issue by enkomio** [B2R2-org/B2R2#31]
**Describe the bug**
Lifting of Intel instruction PCMPESTRI causes an infinite loop.

**To Reproduce**
The following code triggers the infinite loop.
```
let handler = BinHandler.Init(isa, ArchOperationMode.NoMode, false, 0UL, [|0x066uy; 0x00fuy; 0x03auy; 0x063uy; 0x0c1uy; 0x041uy|])
let stmts = 
  match BinHandler.LiftBBlock handler 0UL with
  | Ok (stmts, addr) -> stmts
  | Error (stmts, addr) -> stmts
Console.WriteLine("This code is never reached")
```

Function ``genOutput`` seems to be the cause of the infinite loop.

**Expected behavior**
Valid LowUIR statements are generated

**Environment (please complete the following information):**
 - OS: Windows
 - .NET Core version: 3.1
 - B2R2 version 0.3.1

**Additional context**
The Intel instruction used for the test is: ``pcmpistri xmm0, xmm1, 41h``

**Comment by sangkilc** [comment]
Thanks for the report. This was a known issue and fixed in our internal branch. I will upload the fixed version ASAP.

**Comment by sangkilc** [comment]
bb82fa835ee55bcd16ba757ed7d485af4f4e6abc  fixes the bug.

FYI, the current master branch has some API function changes, which can break your current code potentially. Especially, the AST has been modified to support floating-point operations. We will officially support FP operations later.

**Comment by enkomio** [comment]
Awesome, thank you for the promptly fix! About the potential issues due to the API change, do you have an estimation of the release of the new version? I have another project that uses B2R2 quite extensively and my plan was to upgrade to the new version.

**Comment by sangkilc** [comment]
Our hope is to release it by the end of Apr. But very difficult guarantee it at this moment because we have so many other deadlines 😢
