### ISSUE TITLE
[Question] Any plan for supporting a SMT?

### ISSUE THREAD

**Issue by enkomio** [B2R2-org/B2R2#33]
Is there any plan in the B2R2 roadmap to implement a SMT solver?

This feature would be interesting to have in order to "compete" with other binary analysis projects (like Triton, Angr, ...).

**Comment by sangkilc** [comment]
When you say "implementing a solver" did you mean importing an existing SMT solver into this project? If that's the question, using Z3 is extremely easy in dotnet environment, so I feel like we don't need to embed it into this project. For example, when you are building a symbolic executor with B2R2, what you do is to import both Z3 and B2R2 as a library, and implement your own symbolic executor :)

**Comment by enkomio** [comment]
Awesome!
