### ISSUE TITLE
Improve function detection algorithm

### ISSUE THREAD

**Issue by enkomio** [B2R2-org/B2R2#38]
Hi,
I use regularly this awesome framework and I would like to suggest a possible improvement to the function identification algorithm. In particular, I see that the code is not able to identify indirect calls (I read the code from function ``foldStmts`` in ``BinCorpus``).

I came across a malware that uses static objects. In C++, a static object constructor is called from the ``_initterm`` function. This function uses a table of function pointers that are used to initialize the static objects. Since this table is in the ``.rdata`` section, the call is done indirectly. Here an excerpt of the code calling all the functions inside the table:

```
.text:004217B1                 mov     ecx, eax
.text:004217B3                 call    ds:___guard_check_icall_fptr
.text:004217B9                 call    [ebp+function_pointer]
```

A possible solution would be to apply the algorithm described in https://mistakenot.net/papers/eurosp-2017.pdf, in particular section ``3.2.2 Unreachable/Indirectly Called Functions``.

An example of this malware is: 8bf390bbf31d99d50d719ea8f413338ce5a1e1b3dac4ec58468a707cb7b8e914 (https://www.virustotal.com/gui/file/8bf390bbf31d99d50d719ea8f413338ce5a1e1b3dac4ec58468a707cb7b8e914/detection).

**Comment by sangkilc** [comment]
Hi,

Thanks for the suggestion. Our next version will include the feature of recovering CFGs. So this issue will be resolved by it. We hope to release it by the end of this year with lots of improvements, so please stay tuned!

**Comment by enkomio** [comment]
Awesome!
