### ISSUE TITLE
[Question] Assembling LowUIR to Assembly (x86/x64/...)

### ISSUE THREAD

**Issue by enkomio** [B2R2-org/B2R2#42]
Hi,

I was wondering if you have planned a feature to compile LowUIR code to Assembly (x86/x64/...). I'm aware that is a complex feature but it would be of invaluable importance for the analysis. 

My use case is the creation of an obfuscator that is able to clean a strongly obfuscated binary. An example of obfuscated binary is the malware Emotet (https://cert.grnet.gr/en/blog/reverse-engineering-emotet/) that recently came back. I can deobfuscate the binary by modifying the LowUIR code. What is missing is the binary rebuilding phase, by translating LowUIR to binary code (x86).

At this time, most of the deobfuscators are based on LLVM, which is capable of rebuilding the binary.

**Comment by sangkilc** [comment]
Thanks for the question. That will be a really nice addition to B2R2, but it will require significant engineering effort, so we will not be able to add that feature anytime soon. However, we plan to add a feature that converts LowUIR to LLVM IR. Hope this helps 😉
