### ISSUE TITLE
Error when import function does not exist in wasm binary

### ISSUE THREAD

**Issue by kimdora** [B2R2-org/B2R2#43]
Hello, I'm looking at wasm binary parsing module and it seems there is a bug.

In WebAssembly, import function is not necessary.

You can see an [example](https://github.com/WebAssembly/wabt/blob/main/test/dump/if-multi.txt). This example is in WebAssembly text format and it can directly convert to wasm binary using [wat2wasm](https://webassembly.github.io/wabt/doc/wat2wasm.1.html).

However, please look at the code. If the import function section does not exist, the lengths of the arrays can be different.
```fsharp
// src/FrontEnd/BinFile/WasmParser.fs

  let importedFuncs, impSecOff =
    match wm.ImportSection with
    | Some sec ->
      match sec.Contents with
      | Some conts ->
        conts.Elements
        |> Array.filter (fun ie ->
          match ie.Desc with
          | ImpFunc _ -> true
          | _ -> false
        ), sec.Offset
      | None -> [||], 0
    | None -> [||], 0 // importedFuncs can be [||].
  let lastIdx =
    let len = Array.length importedFuncs
    if len = 0 then 0u // lastIdx can be 0u.
    else uint32 (len - 1)
  let impFuncsIdxMap = // And here is a bug!
    importedFuncs
    |> Array.map2 (fun idx ifun ->
      makeFuncIdxInfo impSecOff idx ifun.Offset) [| 0u .. lastIdx |]
  ```
When `importedFuncs` is `[||]`, `lastIdx` is `0u`. And in `impFuncsIdxMap`, `[| 0u .. lastIdx |]` will be `[| 0u |]`. So there is an error like
```
Error: 배열의 길이가 서로 다릅니다.
array1.Length = 1, array2.Length = 0 (Parameter 'array1')
```

I think we can fix like below.
```fsharp
  let impFuncsIdxMap =
    if Array.isEmpty importedFuncs then [||]
    else
      importedFuncs
      |> Array.map2 (fun idx ifun ->
        makeFuncIdxInfo impSecOff idx ifun.Offset) [| 0u .. lastIdx |]
```

**Comment by sangkilc** [comment]
Hi Doyeon,

Thanks for reporting this. Could you create a PR for this?

**Comment by kimdora** [comment]
I created a PR!
https://github.com/B2R2-org/B2R2/pull/44
