### ISSUE TITLE
Does the B2R2 support PPC32 or Sparc?

### ISSUE THREAD

**Issue by yechenn** [B2R2-org/B2R2#47]
I have successfully built b2r2 and tested it for decompiling languages on the amd64, ARM, and MIPS architectures. However, when I change the "isa" parameter to "ppc32" or "sparc," I encounter errors. Here are examples and the error messages.

**CODE:** 
```
open B2R2
open B2R2.FrontEnd

[<EntryPoint>]
let main argv =
  let isa = ISA.OfString "ppc32"
  let bytes = [| 0x48uy; 0x00uy; 0x00uy; 0x64uy|]
  let hdl = BinHandle.Init (isa, bytes)
  let ins = BinHandle.ParseInstr hdl 0UL
  ins.Translate hdl.TranslationContext |> printfn "%A"
  0
```
or 

```
open B2R2
open B2R2.FrontEnd

[<EntryPoint>]
let main argv =
  let isa = ISA.OfString "sparc"
  let bytes = [| 0x90uy; 0x10uy; 0x20uy; 0x0cuy|]
  let hdl = BinHandle.Init (isa, bytes)
  let ins = BinHandle.ParseInstr hdl 0UL
  ins.Translate hdl.TranslationContext |> printfn "%A"
  0
```
**The same error messages are shown as follows:** 
**ERROR MESSAGE**
```
Unhandled exception. B2R2.InvalidISAException: Exception of type 'B2R2.InvalidISAException' was thrown.
   at B2R2.ISA.OfString(String s)
   at Program.main(String[] argv) in C:\Program Files\dotnet\test1\Program.fs:line 9
```
 I suspect that b2r2 does not support these two architectures, which is why it is throwing this error
But I noticed that there is relevant code for handling the PPC and SPARC architectures in the given GitHub source code. The path is as follows:
_src/FrontEnd/BinLifter/PPC32_
_src/FrontEnd/BinLifter/Sparc64_
### 
So now I don't know how to solve this problem. Can anyone please help me?

**Comment by sangkilc** [comment]
The current version of B2R2 does not fully support SPARC nor PPC, but we will release a new version in a few months, which will include support for both architectures.
