### ISSUE TITLE
Disassembly of relative operands

### ISSUE THREAD

**Issue by tathanhdinh** [B2R2-org/B2R2#6]
Currently, B2R2 uses the current instruction address as base to present the relative target of a `jmp` or `call`, for example `48 31 d8 eb fd` will be disassembled into

```Assembly
0x0        48 31 d8        xor rax, rbx
0x3        eb fd           jmp -0x1 ; 0x2
```

the value `-0x1` means the target is at offset `0x1` w.r.t the current instruction (and this is correct). 

But Intel assembly says that the offset should be computed w.r.t the address of [the next instruction](https://c9x.me/x86/html/file_module_x86_id_147.html), so the result should be displayed as:

```Assembly
0x0        48 31 d8        xor rax, rbx
0x3        eb fd           jmp -0x3 ; 0x2
```
(since `0xfd = -0x3`).

This is just a question to know whether it's the default behaviour of B2R2 (then it's not a bug, just B2R2  assembly is differ from Intel's)

**Comment by sangkilc** [comment]
Think of this as we are following NASM's syntax, but without `$`:
```
jmp $-0x1
```
in NASM corresponds to `eb fd`. We could have only shown the computed address (after semicolon) like other disassemblers, but we output relative offset too with respect to the current instruction, i.e., `$`.

**Comment by tathanhdinh** [comment]
Thanks you for the response. It makes sense to me.
