### ISSUE TITLE
Symbolic Execution component #question

### ISSUE THREAD

**Issue by enkomio** [B2R2-org/B2R2#9]
In section VI.C of the paper there is an interesting discussion on the implementation of a Symbolic Execution prototype. Is this code available? Having something for doing symbolic execution would be very interesting (something like the Sandbox concept in Miasm). 

I see in the code an Eval module but it is marked as Obsolete in the comment. Also, I see two interesting interfaces: *IAbstractInterpreter* and *DomainInterface* but no implementation is provided. Have you any plan on how to implement them? In my opinion is a good part were we can provide contribution

Thanks

**Comment by sangkilc** [comment]
Thanks for the interest!

Actually we are currently planning to begin a startup using our symbolic execution engine, and thus, we don't have a concrete plan when to open-source it. However, we are planning to make some static analyzers public, which are implemented on B2R2, in the near future.

**Comment by sangkilc** [comment]
Will close this issue for now. Feel free to add comments.
